version: 2.1

orbs:
  node: circleci/node@3.0.0

workflows:
  test-deploy:
    jobs:
      - test 


jobs:
  test:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run: node --version
      
